### ISSUE TITLE
npm and nodejs installation

### ISSUE THREAD

**Issue by pwrose** [3dmol/jupyterlab_3Dmol#2]
On a Mac with the Anaconda distribution installed, there is no npm and nodejs available.

I tried to install 
`conda install -c conda-forge nodejs `

and then
`jupyter labextension install jupyterlab_3dmol`

However, that gives the error message below.

Is there a better way to get the extension installed? It's too much of a barrier for Jupyter Lab users.

error An unexpected error occurred: "Received malformed response from registry for undefined. The registry may be down.".
info If you think this is a bug, please open a bug report with the information provided in "/anaconda3/share/jupyter/lab/staging/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> node /anaconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.5.1
(node:763) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ webpack --config webpack.prod.config.js
sh: webpack: command not found
error An unexpected error occurred: "Command failed.
Exit code: 127
Command: sh
Arguments: -c webpack --config webpack.prod.config.js
Directory: /anaconda3/share/jupyter/lab/staging
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/anaconda3/share/jupyter/lab/staging/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by pwrose** [comment]
It looks like others have similar issues:
https://github.com/jupyterlab/jupyterlab/issues/5225

**Comment by dkoes** [comment]
I'm going to close this since it seems to be in issue with jupyterlab, not the jupyterlab_3Dmol extension.
