### ISSUE TITLE
Update project for recent versions of Jupyterlab?

### ISSUE THREAD

**Issue by ulupo** [3dmol/jupyterlab_3Dmol#4]
Installing this extension on recent versions of Jupyterlab broke my Jupyterlab build in a bad way, as documented in https://github.com/jupyterlab/jupyterlab/issues/11631.  As pointed out in https://github.com/jupyterlab/jupyterlab/issues/11631#issuecomment-989288358, perhaps there is a case for refreshing this codebase for compatibility with newer versions of Jupyterlab?  Thanks in advance for your replies!

**Comment by dkoes** [comment]
Okay, I've updated the extension to use more modern versions of basically everything.  See if it works.

Is the extension still needed?  I don't need it installed for py3Dmol to work in my local jupyter lab install and I don't remember the use case that necessitated it in the first place.

**Comment by ulupo** [comment]
Thanks for the lightning quick reply!  Indeed, I just verified that the extension appears not to be actually needed in my jupyterlab install, either.  This is in spite of a warning message that is displayed in old output cells every time I open a session, saying that I should install the extension.  Thanks again!
