### ISSUE TITLE
Incompatibility with Current JupyterLab Version

### ISSUE THREAD

**Issue by smbatyankh** [3dmol/jupyterlab_3Dmol#7]
Hi everyone,

I recently tried to install the `jupyterlab_3dmol@0.1.3` extension on my JupyterLab setup and encountered some dependency conflicts. Here are the details:

```
"jupyterlab_3dmol@0.1.3" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension      Package
>=4.0.7 <4.1.0          >=3.2.5 <4.0.0 @jupyterlab/application
>=4.0.7 <4.1.0          >=3.2.5 <4.0.0 @jupyterlab/notebook
>=7.0.7 <7.1.0          >=6.2.5 <7.0.0 @jupyterlab/services
```

I've reviewed the `package.json` from the repository and it appears the dependency versions might need to be updated to ensure compatibility with recent JupyterLab versions.

Would it be possible to update these dependencies to ensure the extension remains compatible with the latest JupyterLab versions? 

Thanks in advance

**Comment by dkoes** [comment]
I don't think current jupyter lab versions need this extension. Do you find something different? And if so, can you please provide a reproducible test case?

**Comment by smbatyankh** [comment]
I tried running it without the extension, and you're right—it does indeed support 3Dmol.js visualizations without requiring the extension. Thanks for your help!
